eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: cliente
            uri: lb://cliente
            predicates:
              - Path=/api/clientes/**
          - id: cuenta
            uri: lb://cuenta
            predicates:
              - Path=/api/**